### ISSUE TITLE
can it be trained on textlines

### ISSUE THREAD

**Issue by seekingdeep** [OlegPonomaryov/vit-str#1]
hi
can it be trained on textlines instead of words
will it perform well

**Comment by OlegPonomaryov** [comment]
Hi! If by textlines you mean multiple words separated by whitespaces, than, technically, yes, the model can be trained to recognize whitespace just as any other character. However, in terms of performance, as I've mentioned in the training notebook, the model is far from the current state of the art results. You can check out some benchmarks [here](https://github.com/HCIILAB/Scene-Text-Recognition). As you can see, there are some models that achieve 95+% accuracy on the IIIT5K dataset, while this one is just around 80%, so I would definitely recommend using those better models. They are also much better tested on multiple datasets.

**Comment by seekingdeep** [comment]
thanks
