### ISSUE TITLE
Hello, can the dataset be shared via Google Cloud Drive or Baidu.com? Thank you!

### ISSUE THREAD

**Issue by Authen223** [OlegPonomaryov/vit-str#2]

**Comment by Authen223** [comment]
[MJSynth] dataset ，please,thanks~~

**Comment by OlegPonomaryov** [comment]
Sorry, I've played around with this one pretty long ago and don't have it neither on my PC nor anywhere in a cloud storage right now. You'll need to download it directly from their [official site](https://www.robots.ox.ac.uk/~vgg/data/text/).

**Comment by Authen223** [comment]
Okay, thank you~

> Sorry, I've played around with this one pretty long ago and don't have it neither on my PC nor anywhere in a cloud storage right now. You'll need to download it directly from their [official site](https://www.robots.ox.ac.uk/~vgg/data/text/).
https://github.com/OlegPonomaryov/vit-str/issues/2#issuecomment-1476498834
